name: Delivery Throttle

on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  throttle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Throttle Delivery
        env:
          RPM_DT_APISECRET: ${{ secrets.RPM_DT_APISECRET }}
          RPM_DT_GCPKEYJSON: ${{ secrets.RPM_DT_GCPKEYJSON }}
        run: |
          ./.github/workflows/delivery-throttle.sh
