name: Delivery Throttle

on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * *'

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: RutherfordPrimeMeats/workflow-run-cleanup-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  throttle:
    runs-on: ubuntu-latest
    needs: [cancel]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Throttle Delivery
        env:
          TZ: America/New_York
          RPM_DT_APISECRET: ${{ secrets.RPM_DT_APISECRET }}
          RPM_DT_GCPKEYJSON: ${{ secrets.RPM_DT_GCPKEYJSON }}
          RPM_DT_BASEURL: "https://rutherford-prime-meats.myshopify.com/admin/api/2020-10"
          RPM_DT_BLOCKEDDAYS: "2021-12-20,2021-12-21,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2022-1-1,2022-1-10,2022-1-11,2022-1-12,2022-1-13,2022-1-14,2022-1-15,2022-1-16,2022-1-17"
          RPM_DT_MAXORDERS: "20"
          RPM_DT_WARNORDERS: "15"
          RPM_DT_SLEEPTIME: "10m"
          RPM_DT_EXITAFTER: "6h"
          RPM_DT_HEARTBEAT: "9s420ms"
        run: |
          go version
          cd delivery-throttle
          go build .
          ./delivery-throttle || ./delivery-throttle || ./delivery-throttle || ./delivery-throttle
