name: Delivery Throttle

on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  throttle:
    runs-on: ubuntu-latest
    needs: [cancel]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Throttle Delivery
        env:
          TZ: America/New_York
          RPM_DT_APISECRET: ${{ secrets.RPM_DT_APISECRET }}
          RPM_DT_GCPKEYJSON: ${{ secrets.RPM_DT_GCPKEYJSON }}
          RPM_DT_BASEURL: "https://rutherford-prime-meats.myshopify.com/admin/api/2020-10"
          RPM_DT_BLOCKEDDAYS: "2020-12-31,2021-1-1"
          RPM_DT_MAXORDERS: "20"
          RPM_DT_WARNORDERS: "15"
          RPM_DT_SLEEPTIME: "10m"
          RPM_DT_EXITAFTER: "5h"
        run: |
          go version
          cd delivery-throttle
          go run .
