name: Delivery Throttle

on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * *'

concurrency:
  group: delivery-throttle
  cancel-in-progress: true

jobs:
  throttle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      
      - name: Setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Throttle Delivery
        env:
          TZ: America/New_York
          RPM_DT_APISECRET: ${{ secrets.RPM_DT_APISECRET }}
          RPM_DT_GCPKEYJSON: ${{ secrets.RPM_DT_GCPKEYJSON }}
          RPM_DT_HEALTHCHECKURL: ${{ secrets.RPM_DT_HEALTHCHECKURL }}
          RPM_DT_BASEURL: "https://rutherford-prime-meats.myshopify.com/admin/api/2022-04"
          RPM_DT_BLOCKEDDAYS: "2023-8-05,2023-8-06,2023-8-07,2023-8-08,2023-8-09,2023-8-10,2023-8-11,2023-8-12"
          RPM_DT_MAXORDERS: "20"
          RPM_DT_WARNORDERS: "15"
          RPM_DT_SLEEPTIME: "10m"
          RPM_DT_EXITAFTER: "6h"
          RPM_DT_HEARTBEAT: "9s420ms"
        run: |
          go version
          cd delivery-throttle
          go build .
          ./delivery-throttle || ./delivery-throttle || ./delivery-throttle || ./delivery-throttle
